//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_BuscarEndereco
    {
        public string ufe_sg { get; set; }
        public string loc_no { get; set; }
        public Nullable<int> CAD_MUNI_RADAR { get; set; }
        public string bai_no { get; set; }
        public string log_no { get; set; }
        public string cep { get; set; }
        public string log_complemento { get; set; }
        public string nome { get; set; }
    }
}
